package ee.taltech.iti0202.travelagency.enums;

public enum Destination {
    RIGA_LATVIA, TALLINN_ESTONIA, VILNIUS_LITHUANIA, AMSTERDAM_NETHERLANDS,
    BARCELONA_SPAIN, BERLIN_GERMANY, BRUSSELS_BELGIUM, COPENHAGEN_DENMARK,
    DUBLIN_IRELAND, HAMBURG_GERMANY, HELSINKI_FINLAND, KYIV_UKRAINE,
    LONDON_UNITED_KINGDOM, MADRID_SPAIN, MALAGA_SPAIN, MILAN_ITALY,
    MUNICH_GERMANY, OSLO_NORWAY, PALMA_DE_MALLORCA_SPAIN, PARIS_FRANCE,
    REYKJAVIK_ICELAND, STOCKHOLM_SWEDEN, TAMPERE_FINLAND, TBILISI_GEORGIA,
    TEL_AVIV_ISRAEL, VIENNA_AUSTRIA, WARSAW_POLAND, ZURICH_SWITZERLAND
}
